### ISSUE TITLE
Store not loading shipping on I.E.  

### ISSUE THREAD

**Issue by mdius** [concrete5-community-store/community_store#348]
I do not have any shipping options loading on internet explorer. 
www.mdius.com
As guest or logged in.

**Comment by Mesuva** [comment]
I've pushed up a fix for this, which is a one line change: https://github.com/concrete5-community-store/community_store/commit/e843f8eabde230a912112350d1de52a2d01a4cb8

It's a line of code that has been there since the beginning, so I'm surprised this has only been picked up now.

The fix checks to see whether a validation function exists and simply continues on if it doesn't.
Server side validation is in place to check the form fields anyway, so in older IEs you just get less immediate validation feedback.

It would be great if you could confirm this fix for me in IEs (as well as recent browsers)

**Comment by mdius** [comment]
Just updated my store and it still does not work. I am testing with IE 11 on Windows 10.
www.mdius.com

I've tested it on:
Chrome version 64
Edge
Safari 5.1.7 (last windows version)
IE 11, I plan on finding XP with, I believe IE 9 and testing it.

**Comment by mdius** [comment]
Well call me silly.
I had to clear my Cache twice, but that seem to work.
Still trying to find something with an older copy of IE to test it, it does not work at all with IE 6.

**Comment by mdius** [comment]
OK, I am noticing that IE is not adding the shipping.
I'll send screenshots for you.

![microsoft edge](https://user-images.githubusercontent.com/28864099/37217233-03d139fe-238b-11e8-9c27-aebde7e7ccc3.png)

![windows internet explorer](https://user-images.githubusercontent.com/28864099/37217239-0ad217a0-238b-11e8-9df4-99308f3a9444.png)

**Comment by Mesuva** [comment]
I tested this in IE11 and the shipping was added to the total.
But I did find on your site that I had to try a few times to get the shipping option to show up, almost like caching was preventing the page from returning the new options. I'm not sure what you have behind the scenes doing the shipping calc, maybe it's a bit slow to return results.

But from this I'm not replicating the same issue, so I don't have something I can find to fix. 
![screen shot 2018-03-10 at 11 13 01 am](https://user-images.githubusercontent.com/1079600/37236124-a83ba47e-2454-11e8-9cdd-b6c632bc2474.png)

Regarding earlier IE version, IE6 and IE7 aren't considerations anymore (except if you are targeting asian markets), and arguably the same can be said for IE8. Those browsers don't work with the modern way of hosting sites with SSL certificates (using SNI) anyway.  If someone is putting in credit card details into a windows machine running IE6/7/8 I'd be _really_ concerned....

For IE testing, can I suggest the virtual machines at: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/
Download Virtualbox, download those machines and it's easy to quickly fire up a particular version.

**Comment by mdius** [comment]
OK, so I won;t worry about IE 8 and older (kind of wish it worked on IE 8, nothing on my site loads right on IE 8 either). So, I was able to test IE 9. Site loads good, Store loads good, but no shipping option.

![ie 9](https://user-images.githubusercontent.com/28864099/37288504-da480766-25dd-11e8-80fc-591d5a7c71fa.png)

I guess I am not horribly worried about IE 9, I know it is the newest browser Vista offers, but truly how many Vista machines are out there?

I am trying to test Windows 10, not having luck yet. But again, not sure if I care much about IE 10 either. Windows 7 gets IE 11 and I am mostly OK with the shipping showing up like it does, I'd rather make a sale and not charge t he shipping then the person leaving because it doesn't allow them to pass like it did before your fix or like IE 9 seems to still be.

**Comment by Mesuva** [comment]
I believe I've found a fix for this, it was a tricky one to find as it may come down to different servers. I was able to replicate it locally, but not on some of my existing community store installs on IE9.

I believe this is to do with older IEs not thinking they've received a correct response from the server so they don't trigger the next steps - which might be updating the cart total or the shipping options.

Try updating your communityStore.js with the result of this commit:
https://github.com/concrete5-community-store/community_store/commit/5306457d21d219f8a7275195663ab8d9b2b4c226 

File here: https://raw.githubusercontent.com/concrete5-community-store/community_store/5306457d21d219f8a7275195663ab8d9b2b4c226/js/communityStore.js

This may actually fix all the issues that you've described, so please let me know your findings from another test.

**Comment by mdius** [comment]
You did it!!!
It did, it also clear up my IE 11 issue on my Windows 10 machine.

Still wanting to test IE 10, but I assume of 9 & 11 work, it should be just fine.

Thank you very much!

**Comment by Mesuva** [comment]
That's great to hear.
I'll push up another release of community store when we've confirmed there aren't other side effects from my fix.

If you do get a chance to test in other browsers (new and old), and you can confirm that things are working as expected that would be great.

**Comment by mdius** [comment]
Tested on:
Windows 10
Safari for Windows version 5.1.7 (I have no new Apple devices and 5.1.7 I believe was the last version for Windows).
Edge
FireFox Version 58.0.2 x64
Internet Explorer 11
Google Chrome Version 65 x64

Windows XP
FireFox Version 40.0.3
Internet Explorer Version 8 (This version failed)
It would not add product to the cart, it just refreshes the page. But I agreed that this is not an issue and my menu doesn't load right either.

Windows Server 2012 R2
Internet Explorer 11

Windows Vista
FireFox ESR Version 52.6.0
Internet Explorer 9

Andriod 7
Google Chrome Version 64
Edge Version 1.0.0.1656

The layouts all looked good and worked good, I was able to get to add credit card info on all. As I stated Internet Explorer 8 was the only issue.
I'll try a Kindle Fire tonight when I get home and I'll see about trying it on Linux Ubuntu too.

**Comment by mdius** [comment]
OK I thought about it and added testing for

Ubuntu Linux 14.04 x64
Firefox Version 31.0
Updated Firefox Version  58.0.2
Ubuntu Web Browser Version Unknown

CentOS 7.0
Firefox Version 24.5 (Works but the Add to Cart window "cart_modal.php" is at the top of the page and shrank vertically) I would call this acceptable do to OS and old browser version. :-)
Updated Firefox Version  52.6 (Works perfectly)

You were saying something about a different server, I cannot test that unfortunately.

**Comment by Mesuva** [comment]
Sounds like positive results to me, thanks for running through those.
